import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/app/providers/providers";
import Navbar from "@/components/elements/Navbar";

const poppinsBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
});

const poppinsReg = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-reg",
});

const poppinsSemiBold = localFont({
  src: "./fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins-semibold",
});

export const metadata: Metadata = {
  title: "Hakim Nizami",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "dark/logo.svg",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppinsReg.variable} ${poppinsBold.variable} ${poppinsSemiBold.variable} all relative flex justify-center bg-tertiary font-poppins-reg dark:bg-tertiary-dark`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
