import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PoppinsReg = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-PoppinsReg",
});

export const metadata: Metadata = {
  title: "Hakim Nizami",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "logo.svg",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${PoppinsReg.variable}`}>{children}</body>
    </html>
  );
}
